# Generated by Django 2.2.1 on 2019-06-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(choices=[('ME', 'meat'), ('FH', 'fish'), ('FT', 'fruits'), ('MH', 'mushrooms')], default='ME', max_length=2)),
                ('food_price', models.FloatField()),
                ('food_description', models.CharField(max_length=200)),
                ('other_details', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_phone', models.CharField(max_length=20)),
                ('supplier_email', models.CharField(max_length=50)),
                ('other_details', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150)),
                ('zip_postcode', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=150)),
                ('other_details', models.CharField(max_length=350)),
                ('fooditems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooditems.FoodItem')),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooditems.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='locations',
            field=models.ManyToManyField(through='fooditems.Location', to='fooditems.Supplier'),
        ),
    ]
