# Generated by Django 2.2.1 on 2019-06-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='foodtype',
            new_name='food_type',
        ),
    ]
