# Generated by Django 2.2.1 on 2019-06-30 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0002_auto_20190628_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date_delivered',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 13, 43, 51, 935810, tzinfo=utc), verbose_name='Date Delivered'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 13, 43, 51, 935810, tzinfo=utc), verbose_name='Date Ordered'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='order_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='order_delivered',
            field=models.BooleanField(default=True),
        ),
    ]
