# Generated by Django 2.2.1 on 2019-06-30 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0003_auto_20190630_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='date_delivered',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 13, 51, 16, 659390, tzinfo=utc), null=True, verbose_name='Date Delivered'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 13, 51, 16, 659390, tzinfo=utc), null=True, verbose_name='Date Ordered'),
        ),
    ]
