# Generated by Django 2.2.1 on 2019-06-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default=None, max_length=200)),
                ('owner', models.CharField(default=None, max_length=150)),
                ('location', models.CharField(default=None, max_length=200)),
                ('date_established', models.DateField(verbose_name='date established')),
            ],
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_type', models.CharField(choices=[('fo', 'food'), ('dr', 'drinks'), ('ot', 'other items')], default='fo', max_length=2)),
                ('brand', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(default=None)),
                ('price', models.FloatField(default=None)),
                ('date_ordered', models.DateField(verbose_name='date ordered')),
                ('is_available', models.BooleanField(default=True)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.Grocery_store')),
            ],
        ),
    ]
